refactor: convert to typescript
electron-userland/electron-installer-dmg pull request #178
Opened 2022-10-27 09:46 UTC by MarshallOfSound

Converts to typescript so that forge can just import the options type instead of duplicating it

2022-11-09 00:16 UTC, erickzhao requested changes

2022-11-09 00:16 UTC, erickzhao commented on src/index.ts
> +   * Path to the background for the DMG window. Background image should be of size 658x498.
```suggestion
   * Path to the background image for the DMG window. Image should be of size 658x498.
   * If you need to want to add a second Retina-compatible size, add a separate `@2x` image.
   * For example, if your image is called `background.png`, create a `background@2x.png` that is
   * double the size.
```

2022-11-09 00:16 UTC, erickzhao commented on src/index.ts
> +   iconSize?: number;
Is there linting set up for this repo? Seems like there's an extra space on this line.
```suggestion
  iconSize?: number;
```

2022-11-09 00:16 UTC, erickzhao commented on src/index.ts
> +  dmgPath: string;
This should be an optional parameter I think
```suggestion
  dmgPath?: string;
```

2022-11-09 00:16 UTC, erickzhao commented on src/index.ts
> +   * The full path to write the DMG to.
```suggestion
   * The full path to write the DMG to. This option cannot be specified at the same time as `out`.
```

2022-11-09 00:16 UTC, erickzhao commented on src/index.ts
> +   * The directory to put the DMG into. [Default: `process.cwd()`].
```suggestion
   * The directory to put the DMG into. This option cannot be specified at the same time as `dmgPath`.
   * 
   * Defaults to `process.cwd()`.
```

2022-11-11 15:44 UTC, mahnunchik commented
I'm looking forward to have it merged

2024-06-26 18:48 UTC, erickzhao approved these changes

2024-07-02 15:22 UTC, felixrieseberg commented on src/electron-installer-dmg-bin.ts
> +  process.exit(1);
I agree that we shouldn't change this in a TS refactor but this seems like an odd choice, `—help` usually ends in code 0

2024-07-02 15:23 UTC, felixrieseberg approved these changes

2024-07-02 15:28 UTC, merged